Event Handler section translated
vuejs-es/vuejs.org pull request #13
Opened 2017-08-26 05:46 UTC by panietoar

2017-08-26 06:02 UTC, miljan-aleksic requested changes

2017-08-26 06:02 UTC, miljan-aleksic commented on src/v2/guide/events.md
> +<!-- sólo active el manejador si event.target es el elemento en sí -->
en este caso la acción se refiere al evento, por lo que no deberíamos usar la tercera persona pero la segunda. `activa el manejado unicamente si...`

2017-08-26 06:02 UTC, miljan-aleksic commented on src/v2/guide/events.md
> +<!-- p.e. no no de un elemento hijo -->
doble no

2017-08-26 06:02 UTC, miljan-aleksic commented on src/v2/guide/events.md
> +<!-- el evento click será activado al menos una vez -->
No es al menos una vez, al contrario, una vez como mucho. `...será activado una vez como máximo`.

2017-08-26 06:02 UTC, miljan-aleksic commented on src/v2/guide/events.md
> +Puede estar preocupado que toda esta estrategia de escucha de eventos rompe las viejas reglas de "separación de intereses". Puede descansar - ya que todas las funciones y expresiones manejadores está
Mejor `Puede estar tranquilo - `

2017-08-26 06:02 UTC, miljan-aleksic commented on src/v2/guide/events.md
> +3. Cuando un ViewModel es destruído, todos los listeners de eventos son automáticamente eliminados. No tiene que preocuparse de limpiarlo por su cuenta.
`limpiarlos`

2017-08-26 23:00 UTC, panietoar commented on src/v2/guide/events.md
> +3. Cuando un ViewModel es destruído, todos los listeners de eventos son automáticamente eliminados. No tiene que preocuparse de limpiarlo por su cuenta.
hecho, gracias

2017-08-26 23:00 UTC, panietoar commented on src/v2/guide/events.md
> +Puede estar preocupado que toda esta estrategia de escucha de eventos rompe las viejas reglas de "separación de intereses". Puede descansar - ya que todas las funciones y expresiones manejadores está
hecho, gracias

2017-08-26 23:00 UTC, panietoar commented on src/v2/guide/events.md
> +<!-- el evento click será activado al menos una vez -->
hecho, gracias

2017-08-26 23:00 UTC, panietoar commented on src/v2/guide/events.md
> +<!-- p.e. no no de un elemento hijo -->
hecho, gracias

2017-08-26 23:00 UTC, panietoar commented on src/v2/guide/events.md
> +<!-- sólo active el manejador si event.target es el elemento en sí -->
hecho, gracias

2017-08-27 04:45 UTC, miljan-aleksic approved these changes

2017-08-27 04:45 UTC, merged