Form input bindings section translated
vuejs-es/vuejs.org pull request #14
Opened 2017-08-26 23:39 UTC by panietoar

2017-08-27 05:24 UTC, miljan-aleksic requested changes

2017-08-27 05:24 UTC, miljan-aleksic commented on src/v2/guide/forms.md
> +title: Enlace de datos (Binding) en Campos de Formluario
Enlace de datos me suena raro, quizás `Asignaciones de datos en formularios` o `"Binding en formularios"?

Por cierto hay un typo en `Formluario`

2017-08-27 05:24 UTC, miljan-aleksic commented on src/v2/guide/forms.md
> +<p class="tip">`v-model` no se preocupa por el valor inicial dado a un input o textarea. Siempre considera a los datos de instancia de Vue como la fuente de verdad.</p>
`la fuente de la verdad`. Sin el artículo se puede entender de otra manera.

2017-08-27 05:24 UTC, miljan-aleksic commented on src/v2/guide/forms.md
> +<p class="tip" id="vmodel-ime-tip">Para lenguajes que requieren un [IME](https://en.wikipedia.org/wiki/Input_method) (Chino, Japonés, Koreano, etc), se dará cuenta que `v-model` no se actualiza dutan
Typo en `dutante`.

2017-08-27 05:24 UTC, miljan-aleksic commented on src/v2/guide/forms.md
> +<p class="tip">La interpolación en textareas (<code>&lt;textarea&gt;{{text}}&lt;/textarea&gt;</code>)no funcionará. En cambio use<code>v-model</code>.</p>
falta espacio despues de use

2017-08-27 05:24 UTC, miljan-aleksic commented on src/v2/guide/forms.md
> +Para opciones en radios, checkboxes y selects, los valores asignados mediante `v-model` son usualmente strings estáticos (o booleanos para checkbox):
strings => cadenas de texto, me parece es un termino traducible pero lo dejo a debate.

2017-08-27 05:24 UTC, miljan-aleksic commented on src/v2/guide/forms.md
> +<!-- `toggle` es o verdadero o falso -->
le sobra el primero `o`

2017-08-27 05:24 UTC, miljan-aleksic commented on src/v2/guide/forms.md
> +Pero a veces queremos asignar el valor a una propiedad dinánimca de la instancia Vue. Podemos usar `v-bind` para lograr esto. Adicionalmente, usar `v-bind` nos permite asignar el valor del input a va
typo en `dinánimca`

2017-08-27 05:25 UTC, miljan-aleksic commented on src/v2/guide/forms.md
> +> Si los componentes de Vue no le son familiares, sólo salte esta sección por ahora.
el just en inglés suena bien, pero en español mejor `puede saltarse esta sección...`

2017-08-27 15:29 UTC, panietoar commented on src/v2/guide/forms.md
> +title: Enlace de datos (Binding) en Campos de Formluario
hecho, gracias

2017-08-27 15:30 UTC, panietoar commented on src/v2/guide/forms.md
> +<p class="tip">`v-model` no se preocupa por el valor inicial dado a un input o textarea. Siempre considera a los datos de instancia de Vue como la fuente de verdad.</p>
Hecho

2017-08-27 15:30 UTC, panietoar commented on src/v2/guide/forms.md
> +<p class="tip" id="vmodel-ime-tip">Para lenguajes que requieren un [IME](https://en.wikipedia.org/wiki/Input_method) (Chino, Japonés, Koreano, etc), se dará cuenta que `v-model` no se actualiza dutan
Hecho

2017-08-27 15:30 UTC, panietoar commented on src/v2/guide/forms.md
> +<p class="tip">La interpolación en textareas (<code>&lt;textarea&gt;{{text}}&lt;/textarea&gt;</code>)no funcionará. En cambio use<code>v-model</code>.</p>
Gracias

2017-08-27 15:31 UTC, panietoar commented on src/v2/guide/forms.md
> +Para opciones en radios, checkboxes y selects, los valores asignados mediante `v-model` son usualmente strings estáticos (o booleanos para checkbox):
Gracias

2017-08-27 15:31 UTC, panietoar commented on src/v2/guide/forms.md
> +<!-- `toggle` es o verdadero o falso -->
Hecho

2017-08-27 15:32 UTC, panietoar commented on src/v2/guide/forms.md
> +Pero a veces queremos asignar el valor a una propiedad dinánimca de la instancia Vue. Podemos usar `v-bind` para lograr esto. Adicionalmente, usar `v-bind` nos permite asignar el valor del input a va
Hehco

2017-08-27 15:32 UTC, panietoar commented on src/v2/guide/forms.md
> +> Si los componentes de Vue no le son familiares, sólo salte esta sección por ahora.
hecho

2017-08-28 08:07 UTC, miljan-aleksic approved these changes

2017-08-28 08:07 UTC, merged