Instancia Vue translated
vuejs-es/vuejs.org pull request #15
Opened 2017-08-28 16:10 UTC by panietoar

2017-08-28 17:25 UTC, miljan-aleksic requested changes

2017-08-28 17:25 UTC, miljan-aleksic commented on src/v2/guide/instance.md
> +Cada máquina virtual de Vue es inicializada creando una **instancia Vue raíz** con la función constructora `Vue`:
vm se refiere a `ViewModel`

2017-08-28 17:25 UTC, miljan-aleksic commented on src/v2/guide/instance.md
> +Aunqur estrictamente no está asociado con el [patrón MVVM](https://en.wikipedia.org/wiki/Model_View_ViewModel), el diseño de Vue ha sido sin duda inspirado por él, Como convención, a menudo usamos la
- Typo en `Anqur`.
- Falta el punto después de él y antes de Como.

2017-08-28 17:25 UTC, miljan-aleksic commented on src/v2/guide/instance.md
> +En adición a propiedades de datos, las instancias Vue exponen un número de útiles propiedades de instancia y métodos. Estas propiedades y métodos tienen el prefijo `$` para diferenciarlas de propieda
- ´útiles´ debería ir al final, `exponen un número de propiedades de instancia y métodos útiles.`
- Propiedades es masculino, por lo que ´expuestas´ debería ser cambiado acorde.

2017-08-28 17:25 UTC, miljan-aleksic commented on src/v2/guide/instance.md
> +Existen también otros hooks que serán llamados a diferentes estadios del ciclo de vida de la instancia, por ejemplo `mounted`, `updated`, y `destroyed`. Todos los hooks son llamados con su contexto `
`que serán llamados en diferentes puntos del ciclo de vida de la instancia`
`repartida entre estos hooks del ciclo de vida`

2017-08-28 17:25 UTC, miljan-aleksic commented on src/v2/guide/instance.md
> +El siguiente es un diagrama del ciclo de vida de la instancia. No necesita comprender en su totalidad todo lo que está pasando en este momento, pero este diagrama puede serle útil en el futuro.
`No necesita comprender ahora mismo en totalidad todo lo que está pasando, pero este diagrama puede serle útil en el futuro.`

2017-08-29 00:15 UTC, panietoar commented on src/v2/guide/instance.md
> +En adición a propiedades de datos, las instancias Vue exponen un número de útiles propiedades de instancia y métodos. Estas propiedades y métodos tienen el prefijo `$` para diferenciarlas de propieda
Estás seguro que propiedades es masculino?? Los propiedades??
mmmm

2017-08-29 00:17 UTC, panietoar commented on src/v2/guide/instance.md
> +Cada máquina virtual de Vue es inicializada creando una **instancia Vue raíz** con la función constructora `Vue`:
Hecho gracias

2017-08-29 00:17 UTC, panietoar commented on src/v2/guide/instance.md
> +Aunqur estrictamente no está asociado con el [patrón MVVM](https://en.wikipedia.org/wiki/Model_View_ViewModel), el diseño de Vue ha sido sin duda inspirado por él, Como convención, a menudo usamos la
hecho

2017-08-29 00:17 UTC, panietoar commented on src/v2/guide/instance.md
> +Existen también otros hooks que serán llamados a diferentes estadios del ciclo de vida de la instancia, por ejemplo `mounted`, `updated`, y `destroyed`. Todos los hooks son llamados con su contexto `
Hecho

2017-08-29 00:17 UTC, panietoar commented on src/v2/guide/instance.md
> +El siguiente es un diagrama del ciclo de vida de la instancia. No necesita comprender en su totalidad todo lo que está pasando en este momento, pero este diagrama puede serle útil en el futuro.
Hecho

2017-08-29 00:38 UTC, miljan-aleksic commented on src/v2/guide/instance.md
> +En adición a propiedades de datos, las instancias Vue exponen un número de útiles propiedades de instancia y métodos. Estas propiedades y métodos tienen el prefijo `$` para diferenciarlas de propieda
lol, propiedades no, métodos. Me parece que el Español es algo machista y cuando se refiere a un grupo (propiedades y métodos) donde haya al menos un masculino, se usa ese género.

2017-08-29 01:03 UTC, panietoar commented on src/v2/guide/instance.md
> +En adición a propiedades de datos, las instancias Vue exponen un número de útiles propiedades de instancia y métodos. Estas propiedades y métodos tienen el prefijo `$` para diferenciarlas de propieda
jaja ok ok

2017-08-29 01:13 UTC, miljan-aleksic commented on src/v2/guide/instance.md
> +En adición a propiedades de datos, las instancias Vue exponen un número de útiles propiedades de instancia y métodos. Estas propiedades y métodos tienen el prefijo `$` para diferenciarlas de propieda
Perdona, ayer estaba algo cansado, veía algo y no lo analizé bien. `expuestas` es correcto, lo que había que cambiar según la logica de mi expliación anterior es `diferenciarlas` por `diferenciarlos`. Quedando como "Estas propiedades y métodos tienen el prefijo `$` para diferenciarlos de propiedades de `data` expuestas."

2017-08-29 01:30 UTC, panietoar commented on src/v2/guide/instance.md
> +En adición a propiedades de datos, las instancias Vue exponen un número de útiles propiedades de instancia y métodos. Estas propiedades y métodos tienen el prefijo `$` para diferenciarlas de propieda
Dale no hay problema, ya hago el cambio.

2017-08-30 03:30 UTC, miljan-aleksic approved these changes

2017-08-30 03:31 UTC, merged