Introduction Section
vuejs-es/vuejs.org pull request #16
Opened 2017-08-29 16:00 UTC by panietoar

2017-08-30 04:11 UTC, miljan-aleksic requested changes

2017-08-30 04:11 UTC, miljan-aleksic commented on src/v2/guide/index.md
> +Para permitir que los usuarios interactúen con su aplicación, podemos usar la directiva `v-on` para enlazar listeners de eventos que invocan métodos en nuestra instancia Vue:
Listeners es un término nuevo, al parecer. No me convence no traducirlo. ¿Se te ocurre algún termino en Español que tenga sentido?

2017-08-30 04:11 UTC, miljan-aleksic commented on src/v2/guide/index.md
> +Vue también ofrece la directiva `v-model` que hace que un binding bi-direccional entre un campo de formulario y el estado de la aplicación sea muy sencillo:
Sugiero usar `asignación` en vez de `binding` siempre que tenga sentido.

2017-08-30 13:47 UTC, panietoar commented on src/v2/guide/index.md
> +Vue también ofrece la directiva `v-model` que hace que un binding bi-direccional entre un campo de formulario y el estado de la aplicación sea muy sencillo:
Hecho, gracias

2017-08-31 01:44 UTC, miljan-aleksic commented on src/v2/guide/index.md
> +Para permitir que los usuarios interactúen con su aplicación, podemos usar la directiva `v-on` para enlazar listeners de eventos que invocan métodos en nuestra instancia Vue:
Quizás `para enlazar un observador de eventos...`

2017-08-31 04:04 UTC, panietoar commented on src/v2/guide/index.md
> +Para permitir que los usuarios interactúen con su aplicación, podemos usar la directiva `v-on` para enlazar listeners de eventos que invocan métodos en nuestra instancia Vue:
Pues la documentacion de mozilla usa el termino "detector de evento"

https://developer.mozilla.org/es/docs/Web/API/EventTarget/removeEventListener

Aunque tambien usa Listener pero en cursiva.

Me gusta "detector". Opiniones??

2017-08-31 04:40 UTC, miljan-aleksic commented on src/v2/guide/index.md
> +Para permitir que los usuarios interactúen con su aplicación, podemos usar la directiva `v-on` para enlazar listeners de eventos que invocan métodos en nuestra instancia Vue:
Vayamos con Listener en cursiva, pero yo iria con los dos: `event listeners`, así no se crean confusiones.

2017-08-31 05:07 UTC, panietoar commented on src/v2/guide/index.md
> +Para permitir que los usuarios interactúen con su aplicación, podemos usar la directiva `v-on` para enlazar listeners de eventos que invocan métodos en nuestra instancia Vue:
Ok, temprano en la mañana de Colombia haré el cambio. (La traducción de la sección de componentes esta bien pesada jajajaja)

2017-08-31 05:14 UTC, miljan-aleksic approved these changes

2017-08-31 05:15 UTC, miljan-aleksic commented on src/v2/guide/index.md
> +Para permitir que los usuarios interactúen con su aplicación, podemos usar la directiva `v-on` para enlazar listeners de eventos que invocan métodos en nuestra instancia Vue:
Ya me hago cargo :)

Tomate lo con calma, estás haciendo un gran trabajo. Gracias.

2017-08-31 05:15 UTC, merged