Sección Componentes Traducida
vuejs-es/vuejs.org pull request #17
Opened 2017-08-31 14:36 UTC by panietoar

2017-09-03 11:47 UTC, miljan-aleksic requested changes

2017-09-03 11:47 UTC, miljan-aleksic commented on src/v2/guide/components.md
> +Lo cual renderizará:
La cual

2017-09-03 11:47 UTC, miljan-aleksic commented on src/v2/guide/components.md
> +No tiene que registrar globalmente todo componente. Puede hacer que un componente esté disponible únicamente en el ámbito de otro componente/instancia registrándolo con la opción `components` de la i
`No tiene que registrar globalmente todo los componentes`

2017-09-03 11:47 UTC, miljan-aleksic commented on src/v2/guide/components.md
> +Vue se detendrá y emitirá advertencias en la consola, informado que `data` debe ser una función para instancias de componentes. Es bueno comprender por qué esta regla existe, así que hagamos trampa.
`informando`

2017-09-03 11:47 UTC, miljan-aleksic commented on src/v2/guide/components.md
> +  // no se quejará, pero estamos retornando la misma referncia
typo en `referncia`

2017-09-03 11:47 UTC, miljan-aleksic commented on src/v2/guide/components.md
> +Ahora cada uno de nuestros contadores cuentan con su propio estado interno:
`cuentan` => `cuenta`, ya que la expresión es cada **uno**

2017-09-03 11:47 UTC, miljan-aleksic commented on src/v2/guide/components.md
> +Los componentes son para ser usados juntos, de forma más común en relaciones padre-hijo: el componente A puede usar al componente B en su propia plantilla. Ellos inevitablemente necesitarán comunicar
`Los componentes son pensados`

2017-09-03 11:47 UTC, miljan-aleksic commented on src/v2/guide/components.md
> +Los componentes son para ser usados juntos, de forma más común en relaciones padre-hijo: el componente A puede usar al componente B en su propia plantilla. Ellos inevitablemente necesitarán comunicar
`comunicarse unos con otros` => `comunicarse el uno con el otro`

2017-09-03 11:47 UTC, miljan-aleksic commented on src/v2/guide/components.md
> +Ahora podemos enviar un string sencillo al prop de la siguiente forma:
`to it` se refiere al componente, por lo que habria que quitar `al prop`

2017-09-03 11:47 UTC, miljan-aleksic commented on src/v2/guide/components.md
> +Para un componente es posible especificar los requerimientos de los props que serán recibidos. Si un requerimiento no se cumple, Vue emitirá advertencias. Esto es especialmente útil cuando está crean
`está creando un componente que pueda ser usado`

2017-09-03 11:47 UTC, miljan-aleksic commented on src/v2/guide/components.md
> +En vez de definir los props como un arraty de strings, puede usar un objeto con requerimientos de validación:
typo en `arraty`

2017-09-03 11:47 UTC, miljan-aleksic commented on src/v2/guide/components.md
> +      // Emita el valor numérico a travéz del evento input
`travéz` => `través`

2017-09-03 11:47 UTC, miljan-aleksic commented on src/v2/guide/components.md
> +La anterior implementación es bastante sencilla. Por ejemplo, permite a los usuarios ingresar múltiples puntos e incluso letras - ¡desagradable! De modo que para aquellos que quieran ver un ejemplo n
La expresión desagradable no tiene la misma connotación que en Inglés. Quziás se pueda omitir o usar en su lugar `nada deseable`.

2017-09-03 11:47 UTC, miljan-aleksic commented on src/v2/guide/components.md
> +Cuando use componentes, a menudo es requerido componerlos de la siguiente forma:
`Cuando se usan componentes`

2017-09-03 11:47 UTC, miljan-aleksic commented on src/v2/guide/components.md
> +Hay dos cosas que tener en cuenta aquí:
`a tener en cuenta`

2017-09-03 11:47 UTC, miljan-aleksic commented on src/v2/guide/components.md
> +Para hacer que esta composición funcione, necesitamos una forma de entrelazar el "contenido" del padre con la plantilla del componente. Esto es un proceso llamado **distribución de contenido** (o "tr
`borrador  de ...` tiene doble espacio

2017-09-03 11:47 UTC, miljan-aleksic commented on src/v2/guide/components.md
> +El contenido padre será **desechado** a menos que la plantilla del componente hijo contenga al menos un elemento `<outlet>`. Cuando sólo hay un slot sin atributos, el fragmento de contenido entero se
`al menos un elemento `<outlet>` es erróneo, no existen components core `outlet`.

2017-09-03 11:47 UTC, miljan-aleksic commented on src/v2/guide/components.md
> +  <h2>Soy el título hijo</h2>
Soy el título del hijo

2017-09-03 11:47 UTC, miljan-aleksic commented on src/v2/guide/components.md
> +El API de distribución de contenido es un mecanismo múy útil cuando se diseá componentes que deben ir juntos.
typo en `diseá`

2017-09-03 11:47 UTC, miljan-aleksic commented on src/v2/guide/components.md
> +  <!-- ¡el componente cambia siempre que vm.currenView cambie! -->
typo en currenView

2017-09-03 11:47 UTC, miljan-aleksic commented on src/v2/guide/components.md
> +A pesar de la existencia de props y evnetos, algunas veces usted querrá acceder a un componente hijo en JavaScript. Par lograr esto debe asignar un ID de referencia al componente hijo usando `ref`. P
typo en `evnetos` y `Par`

2017-09-03 11:47 UTC, miljan-aleksic commented on src/v2/guide/components.md
> +Los componentes puede invocarse a sí mismos recursivamente en su propia plantilla. Sin embargo, sólo puede hacerlo mediante la opción `name`:
`Los componentes puede` =>  `Los componentes pueden`

2017-09-03 11:47 UTC, miljan-aleksic commented on src/v2/guide/components.md
> +Un componente como el anterior resultará en un error "tamaño máximo de la pila ha sido excedido", de modo que asegúrese que la invocación recursiva es condicional (p.e. usa un `v-if` el cual eventual
`usa un` => `use un`

2017-09-03 11:47 UTC, miljan-aleksic commented on src/v2/guide/components.md
> +Cuando el atributo especial `inline-template` está presente en un componente hijo, el componente usará su contenido interno como su plantilla, en lugar de tratarlo como contenido distribuído. Esto pe
distribuído no lleva tilde

2017-09-03 11:47 UTC, miljan-aleksic commented on src/v2/guide/components.md
> +Renderizar elementos HTML simples es muy rápido en Vue, pero a veces querrá tener un componente que incluya **mucho** contenido estático. En aquellos casos, puede asegurarse que sólo sea evaluado una
`En aquellos casos` => `En esos casos`

2017-09-04 14:45 UTC, panietoar commented on src/v2/guide/components.md
> +Renderizar elementos HTML simples es muy rápido en Vue, pero a veces querrá tener un componente que incluya **mucho** contenido estático. En aquellos casos, puede asegurarse que sólo sea evaluado una
Hecho

2017-09-04 14:45 UTC, panietoar commented on src/v2/guide/components.md
> +Cuando el atributo especial `inline-template` está presente en un componente hijo, el componente usará su contenido interno como su plantilla, en lugar de tratarlo como contenido distribuído. Esto pe
Hecho

2017-09-04 14:45 UTC, panietoar commented on src/v2/guide/components.md
> +Un componente como el anterior resultará en un error "tamaño máximo de la pila ha sido excedido", de modo que asegúrese que la invocación recursiva es condicional (p.e. usa un `v-if` el cual eventual
Hecho

2017-09-04 14:45 UTC, panietoar commented on src/v2/guide/components.md
> +Los componentes puede invocarse a sí mismos recursivamente en su propia plantilla. Sin embargo, sólo puede hacerlo mediante la opción `name`:
Hecho

2017-09-04 14:45 UTC, panietoar commented on src/v2/guide/components.md
> +A pesar de la existencia de props y evnetos, algunas veces usted querrá acceder a un componente hijo en JavaScript. Par lograr esto debe asignar un ID de referencia al componente hijo usando `ref`. P
Hecho

2017-09-04 14:45 UTC, panietoar commented on src/v2/guide/components.md
> +El API de distribución de contenido es un mecanismo múy útil cuando se diseá componentes que deben ir juntos.
Hecho

2017-09-04 14:45 UTC, panietoar commented on src/v2/guide/components.md
> +El contenido padre será **desechado** a menos que la plantilla del componente hijo contenga al menos un elemento `<outlet>`. Cuando sólo hay un slot sin atributos, el fragmento de contenido entero se
Hecho

2017-09-04 14:45 UTC, panietoar commented on src/v2/guide/components.md
> +Para hacer que esta composición funcione, necesitamos una forma de entrelazar el "contenido" del padre con la plantilla del componente. Esto es un proceso llamado **distribución de contenido** (o "tr
Hecho

2017-09-04 14:45 UTC, panietoar commented on src/v2/guide/components.md
> +Hay dos cosas que tener en cuenta aquí:
Hecho

2017-09-04 14:45 UTC, panietoar commented on src/v2/guide/components.md
> +Cuando use componentes, a menudo es requerido componerlos de la siguiente forma:
Hecho

2017-09-04 14:45 UTC, panietoar commented on src/v2/guide/components.md
> +La anterior implementación es bastante sencilla. Por ejemplo, permite a los usuarios ingresar múltiples puntos e incluso letras - ¡desagradable! De modo que para aquellos que quieran ver un ejemplo n
Hecho

2017-09-04 14:45 UTC, panietoar commented on src/v2/guide/components.md
> +      // Emita el valor numérico a travéz del evento input
Hecho

2017-09-04 14:45 UTC, panietoar commented on src/v2/guide/components.md
> +Para un componente es posible especificar los requerimientos de los props que serán recibidos. Si un requerimiento no se cumple, Vue emitirá advertencias. Esto es especialmente útil cuando está crean
Hecho

2017-09-04 14:45 UTC, panietoar commented on src/v2/guide/components.md
> +Los componentes son para ser usados juntos, de forma más común en relaciones padre-hijo: el componente A puede usar al componente B en su propia plantilla. Ellos inevitablemente necesitarán comunicar
Hecho

2017-09-04 14:46 UTC, panietoar commented on src/v2/guide/components.md
> +Ahora cada uno de nuestros contadores cuentan con su propio estado interno:
Hecho

2017-09-04 14:46 UTC, panietoar commented on src/v2/guide/components.md
> +  // no se quejará, pero estamos retornando la misma referncia
Hecho

2017-09-04 14:46 UTC, panietoar commented on src/v2/guide/components.md
> +Vue se detendrá y emitirá advertencias en la consola, informado que `data` debe ser una función para instancias de componentes. Es bueno comprender por qué esta regla existe, así que hagamos trampa.
Hecho

2017-09-04 14:46 UTC, panietoar commented on src/v2/guide/components.md
> +No tiene que registrar globalmente todo componente. Puede hacer que un componente esté disponible únicamente en el ámbito de otro componente/instancia registrándolo con la opción `components` de la i
Hecho

2017-09-04 14:46 UTC, panietoar commented on src/v2/guide/components.md
> +Lo cual renderizará:
Hecho

2017-09-04 14:46 UTC, panietoar commented
Increíble la cantidad de cosas pequeñas que se la pasan a uno jaja.

Muchas gracias por la revisión @miljan-aleksic

2017-09-04 14:49 UTC, miljan-aleksic approved these changes

2017-09-04 14:50 UTC, merged