Transiciones
vuejs-es/vuejs.org pull request #19
Opened 2017-09-08 15:48 UTC by panietoar

2017-09-09 04:20 UTC, miljan-aleksic requested changes

2017-09-09 04:20 UTC, miljan-aleksic commented on src/v2/guide/transitions.md
> +Vue ofrece una variedad de maneras para aplicar efectos de transición siempre que los elementos sean insertados, actualizados o eliminados del DOM. Esto incluye herramientas para:
`...de transición cuando los elementos son insertados...`

2017-09-09 04:20 UTC, miljan-aleksic commented on src/v2/guide/transitions.md
>  ![Transition Diagram](/images/transition.png)
El ALT de esta imagen lo podríamos traducir también.

2017-09-09 04:20 UTC, miljan-aleksic commented on src/v2/guide/transitions.md
> +Usted también peude especificar clases de transición personalizadas cuando usa los siguientes atributos:
typo en `peude`

2017-09-09 04:20 UTC, miljan-aleksic commented on src/v2/guide/transitions.md
> +Aquí hay un ejemplo:
Aquí hay un ejemplo => Por ejemplo

En español queda raro decir aquí hay un ejemplo, no?

2017-09-09 04:20 UTC, miljan-aleksic commented on src/v2/guide/transitions.md
> +Vue necesita agregar listeners de eventos para poder saber cuándo una transición ha finalizado. Puede ser mediante `transitionended` o `animationended`, dependiendo del tipo de reglas CSS aplicadas.
Las palabras sin traducir dejalas en cursiva. Ej listeners

2017-09-09 04:20 UTC, miljan-aleksic commented on src/v2/guide/transitions.md
> +Por defecto, el usará la transición especificada para entrada y salida. Sin embargo, si lo quisiera, puede también especificar clases CSS personalizadas:
`el usará`? quién es él? Mejor usar `esto` o similar.

2017-09-09 04:20 UTC, miljan-aleksic commented on src/v2/guide/transitions.md
> +<p class="tip">Cuano intercambia elementos que tienen el **mismo nombre de etiqueta**, debe decirle a Vue que ellos son elementos diferentes usando atributos `key` únicos. De otra forma, el compilado
typo en `Cuano`

2017-09-09 04:20 UTC, miljan-aleksic commented on src/v2/guide/transitions.md
> +Es posible realizar una transición entre cualquier número de elementos, ya sea usando muchos `v-if`, o asignando una propiedad dinámina a un elemento. Por ejemplo:
typo en `dinámina`

2017-09-09 04:20 UTC, miljan-aleksic commented on src/v2/guide/transitions.md
> +- A diferencia de `<transicion>`, renderiza un elemento `<span>` por defecto. Puede cambiar el elemento que es renderizado con el atributo `tag`.
<transicion> => <transition>

2017-09-09 04:20 UTC, miljan-aleksic commented on src/v2/guide/transitions.md
> +<p class="tip">Algo importante para tener en cuenta es que éstas transiciones FLIP no funcionan con elementos con `display: inline`. Como alternativa, puede usar `display: inline-block` o ubicar los
`con elementos con` queda redundante. Propongo `en elementos con`

2017-09-09 04:20 UTC, miljan-aleksic commented on src/v2/guide/transitions.md
> +Estas animaciones FLIP no están limitadas a un eje particular. Los elementos en una grilla multidimencional puede realizar transiciones [igual de fácil](https://jsfiddle.net/chrisvfritz/sLrhk1bc/):
multidimencional > multidimensional
puede > pueden

2017-09-09 04:20 UTC, miljan-aleksic commented on src/v2/guide/transitions.md
> +Si, ¡incluso las transiciones en Vue son controladas por datos! El ejemplo más básico de una transición dinámica es asignar el atributo `name` a una propiedad dinámica.
Si, ¡incluso > Sí, ¡incluso

2017-09-11 14:57 UTC, panietoar commented
Comentarios resueltos.

Gracias!

2017-09-11 16:47 UTC, miljan-aleksic approved these changes

2017-09-11 16:48 UTC, merged