Sintaxis de Plantilla
vuejs-es/vuejs.org pull request #21
Opened 2017-09-08 17:06 UTC by panietoar

2017-09-09 04:38 UTC, miljan-aleksic requested changes

2017-09-09 04:38 UTC, miljan-aleksic commented on src/v2/guide/syntax.md
> +title: Sitaxis de Plantilla
Typo: Sitaxis > Sintaxis

2017-09-09 04:38 UTC, miljan-aleksic commented on src/v2/guide/syntax.md
> +Vue.js usa una sintaxis de plantillas basadas en HTML que le permite asignar declarativamente el DOM renderizado a los datos de la instancia de Vue. Todas las plantillas de Vue.js son HTML válido que
sintaxis de plantillas > sintaxis de plantilla

2017-09-09 04:38 UTC, miljan-aleksic commented on src/v2/guide/syntax.md
> +Usted también puede realizar interpolaciones de única-vez que no se actualizan cuando los datos cambian si usa la [directiva v-once](../api/#v-once), pero tenga en cuenta que esto también afectará ot
`de única-vez` queda raro. Lo podemos omitir: `interpolaciones que no se actualizan cuando los datos cambian`

2017-09-09 04:38 UTC, miljan-aleksic commented on src/v2/guide/syntax.md
> +También funciona para atributos booleanos - el atributo será eliminado si la condición se resuelve en un valor falsy:
booleanos y falsy en cursiva

2017-09-09 04:38 UTC, miljan-aleksic commented on src/v2/guide/syntax.md
> +Estas expresiones serán evaluadas como JavaScript en el ámbito de datos del propietario de la instancia Vue. Una restricción es que cada asignación puede contener únicamente **una expresión individua
Esto `en el ámbito de datos del propietario de la instancia Vue` es confuso, simplifiquemos los a `en el ámbito de datos de la instancia Vue`.

2017-09-09 04:38 UTC, miljan-aleksic commented on src/v2/guide/syntax.md
> +<p class="tip">Las expresiones de plantillas son controladas y sólo tienen acceso a una lista curada de expresiones globales como `Math` y `Date`. Usted no debe intentar acceder globales definidas po
expresiones de plantillas > expresiones de plantilla

2017-09-09 04:38 UTC, miljan-aleksic commented on src/v2/guide/syntax.md
> +Aquí, la directiva `v-if` eliminará/insertará el elemento `<p>` basado en el valor de verdad de la expresión `seen`.
basado en el valor de verdad de la expresión > basado en el valor de la expresión

2017-09-09 04:38 UTC, miljan-aleksic commented on src/v2/guide/syntax.md
> +Algunas directivas pueden tomar un "argumento", denotado con el carácter de dos puntos después del nombre de la directiva. Por ejemplo, la directiva `v-bin` es usada para actualizar reactivamente un
`v-bin` > `v-bind`

2017-09-09 04:38 UTC, miljan-aleksic commented on src/v2/guide/syntax.md
> +Veremos más usos de los modificadores más adelante cuando vemos en detalle a `v-on` y `v-model`.
"Veremos más usos de los modificadores más adelante cuando repasemos con más detalle `v-on` y `v-model`."

2017-09-11 14:49 UTC, panietoar commented
Todos los comentarios han sido hechos

2017-09-11 16:38 UTC, merged