Traducción sección Global API
vuejs-es/vuejs.org pull request #22
Opened 2017-09-12 16:37 UTC by panietoar

2017-09-12 23:54 UTC, miljan-aleksic requested changes

2017-09-12 23:54 UTC, miljan-aleksic commented on src/v2/api/index.md
> +  // mnodificar datos
typo

2017-09-12 23:54 UTC, miljan-aleksic commented on src/v2/api/index.md
> +  > Nuevo en 2.1.0: retorna un *Promise* si no se ha especificado una función *callback* y en el ambiente de ejecución los *Promise* son soportados.
En algunas traducciones técnicas he visto que traducen el termino *callback* como retorno de llamada. ¿Qué te parece usarlo? Así como traducir Promise como Promesa.

2017-09-12 23:54 UTC, miljan-aleksic commented on src/v2/api/index.md
> +- **Ver También:** [Reactividad a Profundidad](../guide/reactivity.html)
> Reactividad en profundidad

2017-09-12 23:54 UTC, miljan-aleksic commented on src/v2/api/index.md
> +  Elimina una propiedad de un objeto. Si el objeto es reactivo, asegúrese que dicha eliminación active una actualización de vista. Esto se usa principalmente para resolver el problema que Vue no pued
`Si el objeto es reactivo, asegúrese...`, no se refiere a que el usuario se asegure, si no que Vue.delete se asegura que se activen las actualizaciones (en plural). Por lo que debería ser:

`Elimina una propiedad de un objeto. Si el objeto es reactivo, se asegura que dicha eliminación active las actualizaciones de vista. Esto se usa principalmente para resolver el problema que Vue no puede detectar eliminaciones de propiedades en objetos, pero usted tendrá muy poca necesidad de usarlo.`

2017-09-12 23:54 UTC, miljan-aleksic commented on src/v2/api/index.md
> +- **Vea También:** [Directivas Personalizadas](../guide/custom-directive.html)
En Español no se usan mayuscaulas en los títulos como en Inglés. ... > Directivas personalizadas

2017-09-12 23:54 UTC, miljan-aleksic commented on src/v2/api/index.md
> +  Registra u obtiene un componente global. El registro también asigna automáticamente el `id` dado al atributo `name` del componente.
> El registro también asigna automáticamente el `name` del componente con el `id` especificado.

2017-09-12 23:54 UTC, miljan-aleksic commented on src/v2/api/index.md
> +- **Vea También:** [Components](../guide/components.html)
Components > Componentes

2017-09-12 23:54 UTC, miljan-aleksic commented on src/v2/api/index.md
> +- **Vea También:** [Directivas Personalizadas](../guide/custom-directive.html)
Mira de corregirlo en todo el documento porfavor.

2017-09-12 23:54 UTC, miljan-aleksic commented on src/v2/api/index.md
> +- **Vea También:** [Reactivity in Depth](../guide/reactivity.html)
[Reactividad en profundidad]

2017-09-12 23:54 UTC, miljan-aleksic commented on src/v2/api/index.md
>    - [Computed Properties](../guide/computed.html)
[Propiedades computadas]

2017-09-12 23:54 UTC, miljan-aleksic commented on src/v2/api/index.md
> +- **Vea También:** [Methods and Event Handling](../guide/events.html)
Falta traducir el ALT

2017-09-12 23:54 UTC, miljan-aleksic commented on src/v2/api/index.md
> +- **Vea También:** [Methods and Event Handling](../guide/events.html)
Mira de traducir todos los que faltan por favor.

2017-09-13 13:56 UTC, panietoar commented on src/v2/api/index.md
> +  > Nuevo en 2.1.0: retorna un *Promise* si no se ha especificado una función *callback* y en el ambiente de ejecución los *Promise* son soportados.
el de callback me parece aunque considero que callback es un nombre más familiar en el ámbito de desarrollo JavaScript.
Pero Promise a Promesa no me parece, el documento se refiere a un objeto tipo Promise de JavasScript:
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise

2017-09-13 13:57 UTC, panietoar commented on src/v2/api/index.md
> +  Elimina una propiedad de un objeto. Si el objeto es reactivo, asegúrese que dicha eliminación active una actualización de vista. Esto se usa principalmente para resolver el problema que Vue no pued
Oops, completamente deacuerdo.

2017-09-13 14:06 UTC, miljan-aleksic commented on src/v2/api/index.md
> +  > Nuevo en 2.1.0: retorna un *Promise* si no se ha especificado una función *callback* y en el ambiente de ejecución los *Promise* son soportados.
Deacuerdo.

2017-09-15 15:35 UTC, panietoar commented on src/v2/api/index.md
> +  // mnodificar datos
Done

2017-09-15 15:37 UTC, panietoar commented on src/v2/api/index.md
> +- **Ver También:** [Reactividad a Profundidad](../guide/reactivity.html)
Done

2017-09-15 15:37 UTC, panietoar commented on src/v2/api/index.md
> +  Elimina una propiedad de un objeto. Si el objeto es reactivo, asegúrese que dicha eliminación active una actualización de vista. Esto se usa principalmente para resolver el problema que Vue no pued
Done

2017-09-15 15:38 UTC, panietoar commented on src/v2/api/index.md
> +- **Vea También:** [Directivas Personalizadas](../guide/custom-directive.html)
Done

2017-09-15 15:38 UTC, panietoar commented on src/v2/api/index.md
> +  Registra u obtiene un componente global. El registro también asigna automáticamente el `id` dado al atributo `name` del componente.
Done

2017-09-15 15:39 UTC, panietoar commented on src/v2/api/index.md
> +- **Vea También:** [Components](../guide/components.html)
Done

2017-09-15 15:50 UTC, miljan-aleksic commented
No veo ningún nuevo commit pero si tus comentarios. Se te habrá pasado subirlo online?

2017-09-15 16:00 UTC, panietoar commented
Los cambios será cometidos cuando termine la sección Options/Data @miljan-aleksic, en unos cuantos minutos.

2017-09-18 08:59 UTC, miljan-aleksic approved these changes

2017-09-18 08:59 UTC, merged