Translation to Spanish [#1] 594 Words
vuejs-es/vuejs.org pull request #35
Opened 2018-03-03 18:02 UTC by Santu41

Cerré el antiguo pull request para poder poner las dos columnas juntas dentro de uno. Ambos están traducidos completamente al español y esperando corrección! saludos.. :100:

2018-03-04 04:15 UTC, miljan-aleksic commented
De nuevo muchas gracias @Santu41. Se me pasó por alto mencionarte las [Pautas de Traducción](https://github.com/vuejs-es/vuejs.org/wiki/Pautas-de-Traducci%C3%B3n), las cuales entre todos vamos mejorando.

Me he tomado la libertad de aplicar mi revisión directamente en tu repositorio para el mixins.md y me gustaría que en base a ello y las pautas mencionadas hagas tu mismo la revisión de Plugins.md.

2018-03-05 22:02 UTC, Santu41 commented
Post corregido, espero no tener errores y de ser así poder ir mejorando en el transcurso del proyecto! saludos

2018-03-06 02:48 UTC, miljan-aleksic requested changes
Gracias! Aquí va mi revisión :)

2018-03-06 02:48 UTC, miljan-aleksic commented on src/v2/guide/plugins.md
> +2. Agregar uno o más recursos globales: directivas / filtros / transiciones, etc. Por ejemplo [vue-touch](https://github.com/vuejs/vue-touch)
Creo que es mejor seguir las mismas pautas de espaciado del texto original. La frase debería quedar como `Agregar uno o más recursos globales: directivas/filtros/transiciones, etc. Por ejemplo [vue-touch](https://github.com/vuejs/vue-touch)`

2018-03-06 02:48 UTC, miljan-aleksic commented on src/v2/guide/plugins.md
Me parece que este espacio sobra.

2018-03-06 02:48 UTC, miljan-aleksic commented on src/v2/guide/plugins.md
> +Un Plugin Vue.js debería exponer un método `instalar` (Método de instalación). Se llamará al método con el constructor `Vue` como primer argumento, junto con las posibles opciones:
En este caso `install` no lo podemos traducir ya que es literalmente el nombre que Vue espera que el método tenga. Me parece bien dejar la traducción entre paréntesis pero tan solo `(instalar)`.

2018-03-06 02:48 UTC, miljan-aleksic commented on src/v2/guide/plugins.md
> +MyPlugin.install = función (opciones de Vue) {
Para los ejemplos de código tan solo traducimos los comentarios asegurando que los mismos sigan siendo ejecutables.

2018-03-06 02:48 UTC, miljan-aleksic commented on src/v2/guide/plugins.md
> +  // 3. inyectar algunas opciones de componentes
Respetemos los plurales/singulares originales -  `inyectar algunas opciones de componente`

2018-03-06 02:48 UTC, miljan-aleksic commented on src/v2/guide/plugins.md
>  // calls `MyPlugin.install(Vue)`
por traducir

2018-03-06 02:48 UTC, miljan-aleksic commented on src/v2/guide/plugins.md
> +Puede si lo desea descartar algunas opciones:
Hay un malentendimiento aquí. La traducción correcta sería `Opcionalmente puede declarar algunas opciones:`

2018-03-06 02:48 UTC, miljan-aleksic commented on src/v2/guide/plugins.md
> +`Vue.use` automáticamente lo previene de usar el mismo Plugin más de una vez, por lo que, al llamar varias veces a un mismo Plugin, este se instalará solo una vez.
Sugerencia: `...por lo que, al usarlo varias veces con el mismo Plugin, este se instalará solo una vez.`

2018-03-06 02:48 UTC, miljan-aleksic commented on src/v2/guide/plugins.md
> +Algunos Plugins proporcionados por “Vue.js official plugins” como `vue-router`, citan automáticamente a `Vue.use ()` si `Vue` está disponible como una variable global. Sin embargo, en un módulo como
Emplea "llamar" o "ejecutar" envez de "citar". Creo que se entiende mejor.

2018-03-06 02:48 UTC, miljan-aleksic commented on src/v2/guide/plugins.md
> +// Cuando usa CommonJS via Browserify o Webpack
`Cuando use...`

2018-03-06 02:48 UTC, miljan-aleksic commented on src/v2/guide/plugins.md
> +Consulte [awesome-vue](https://github.com/vuejs/awesome-vue#components--libraries)para obtener una gran colección de plugins y librerías proporcionados por la comunidad.
Cuidado con los espacios, falta uno después del enlace.

2018-03-06 03:11 UTC, Santu41 commented
Todo arreglado! no entendí muy bien esto:
Para los ejemplos de código tan solo traducimos los comentarios asegurando que los mismos sigan siendo ejecutables.
pero lo demás perfecto, espero que me asignen una nueva columna, saludos!

2018-03-06 03:19 UTC, miljan-aleksic approved these changes

2018-03-06 03:22 UTC, merged

2018-03-06 03:25 UTC, miljan-aleksic commented
Me refería a que los codigo de ejemplo tienen que funcionar si se copian y usan, ser ejecutables. Si traducimos la logica ya no son ejecutables. Por lo que solo traducimos los comentarios.

Gracias por tu colaboración @Santu41. Te he asignado "Deploying for Production" :)