Traducción Global Config
vuejs-es/vuejs.org pull request #6
Opened 2016-12-18 16:19 UTC by zgudino

Buenas,

Adjunto PR con la traducción [Global Config](https://github.com/vuejs-es/vuejs.org/projects/1#card-1001821) respecto documentación API.
Gracias!

2016-12-19 00:56 UTC, miljan-aleksic commented
Mira de corregir los merging conflicts. Y dime si al final aceptamos no tutear o seguimos :)

2016-12-19 12:41 UTC, miljan-aleksic requested changes

2016-12-19 12:41 UTC, miljan-aleksic commented on src/v2/api/index.md
> +  La estrategia de combinación recibe el valor de esa opción definida en las instancias padre e hijo como primer y segundo argumentos, respectivamente. La instancia Vue de contexto se pasa como terce
>...como primer y segundo argumentos.

No estoy del todo seguro, pero en español debería ser todo en singular en este caso.

2016-12-19 12:41 UTC, miljan-aleksic commented on src/v2/api/index.md
> +  // asegurate de configurarlo de forma sincronizada inmediatamente después de cargar Vue
`asegúrate` lleva accento.

2016-12-19 12:41 UTC, miljan-aleksic commented on src/v2/api/index.md
> +  Configura si deseas permitir inspección [vue-devtools](https://github.com/vuejs/vue-devtools). El valor por defecto de esta opcion es `true` en compilaciones de desarrollo y `false` en compilacione
>Configure whether to allow [vue-devtools](https://github.com/vuejs/vue-devtools) inspection.

El texto hace referencia a la opción, no al usuario. Una traducción mas adecuada sería

>Configura el permiso de inspección de  [vue-devtools](https://github.com/vuejs/vue-devtools).

2016-12-19 12:41 UTC, miljan-aleksic commented on src/v2/api/index.md
> +- **Por defecto:** Lanza un error en vez
No acabo de entender esta traducción. Recomiendo `El error es producido en el lugar`.

@llops, qué opinas de usar `error producido` para `thrown error`. Lo añado a las pautas o tienes alguna mejor sugerencia?

2016-12-19 12:41 UTC, miljan-aleksic commented on src/v2/api/index.md
> +  Asigna un manejador para errores no detectados durante render y watchers del componente. El manejador es llamado con el error y la instancia Vue.
Manejador suena bien extraño. A ver si encontramos mejor traducción.

@llops, 'render' y 'watchers' parecen ser terminos a no traducir. Aunque no parecen cuajar muy bien aquí tal cual...

2016-12-19 12:41 UTC, miljan-aleksic commented on src/v2/api/index.md
> +  Haz que Vue ignore elementos personalizados definidos fuera de Vue (e.g., utilizando los APIs de Web Components). De lo contrario, lanzará una advertencia sobre un `Unknown custom element`, suponie
Prueba de añadir además la cursiva a `Unknown custom element`, ya que es un término sin traducir.

2016-12-20 14:42 UTC, llops requested changes
¡Ahí van mis sugerencias!

Y de manera general:
Verbos:  emplear la 3ª persona del presente subjuntivo (Inicie por inicia, etc.)
Sustituir el tuteo por el tratamiento de usted.

Buen trabajo Zahir :)

2016-12-20 14:42 UTC, llops commented on src/v2/api/index.md
> +  La estrategia de combinación recibe el valor de esa opción definida en las instancias padre e hijo como primer y segundo argumentos, respectivamente. La instancia Vue de contexto se pasa como terce
Concuerdo con Miljan.

2016-12-20 14:42 UTC, llops commented on src/v2/api/index.md
> +`Vue.config` es un objeto que contiene las configuraciones globales de Vue. Puedes modificar sus propiedades enumeradas a continuación antes de iniciar tu aplicación:
Cambiar tiempo verbal (Puede modificar).
Cambiar posesivo (... iniciar su aplicación)

2016-12-20 14:42 UTC, llops commented on src/v2/api/index.md
> +`Vue.config` es un objeto que contiene las configuraciones globales de Vue. Puedes modificar sus propiedades enumeradas a continuación antes de iniciar tu aplicación:
Ésta es un poco puntillosa, pero realmente sería así:
> Puede modificar sus propiedades, enumeradas a continuación, antes de iniciar su aplicación:

O si queremos hacerlo más natural, yo obviaría el "its" para hablar del listado de propiedades:
> Puede modificar las propiedades enumeradas a continuación antes de iniciar su aplicación:

2016-12-20 14:42 UTC, llops commented on src/v2/api/index.md
> +  La estrategia de combinación recibe el valor de esa opción definida en las instancias padre e hijo como primer y segundo argumentos, respectivamente. La instancia Vue de contexto se pasa como terce
Propongo para _merge_ utilizar _fusión_. Más info aquí: https://github.com/vuejs-es/vuejs.org/issues/1#issuecomment-268241296

2016-12-20 14:42 UTC, llops commented on src/v2/api/index.md
> +  // asegurate de configurarlo de forma sincronizada inmediatamente después de cargar Vue
Cambiar tiempo verbal (asegúrese)

2016-12-20 14:42 UTC, llops commented on src/v2/api/index.md
> +  Configura si deseas permitir inspección [vue-devtools](https://github.com/vuejs/vue-devtools). El valor por defecto de esta opcion es `true` en compilaciones de desarrollo y `false` en compilacione
Cambiar tiempo verbal (Puede configurarlo)

2016-12-20 14:42 UTC, llops commented on src/v2/api/index.md
> +- **Por defecto:** Lanza un error en vez
Lo más común es _Lanza_ o _Genera_.
Lo de "en vez" tampoco lo entiendo. Yo usaría:

> Lanza un error en el momento / Genera un error en el momento

Lo del "momento" no estoy 100% seguro, pero me suena más natural en español hablar de "tiempo" vs "lugar": "en tiempo de compilación", etc. Como veáis ;)

2016-12-20 14:42 UTC, llops commented on src/v2/api/index.md
> +  Asigna un manejador para errores no detectados durante render y watchers del componente. El manejador es llamado con el error y la instancia Vue.
"Manejador" es verdad que suena raro, pero la traducción es correcta y se emplea en la mayoría de sitios.

2016-12-20 14:42 UTC, llops commented on src/v2/api/index.md
> +  Asigna un manejador para errores no detectados durante render y watchers del componente. El manejador es llamado con el error y la instancia Vue.
Sí, queda muy poco natural no traducirlos. Yo optaría por:
> ... durante el renderizado y la observación (watcher) del componente.

Renderizado me parece muy común. Observación me suena bien, pero mantendría el _watcher_ ya que el código se emplea tal cual.

2016-12-20 14:42 UTC, llops commented on src/v2/api/index.md
> +  Haz que Vue ignore elementos personalizados definidos fuera de Vue (e.g., utilizando los APIs de Web Components). De lo contrario, lanzará una advertencia sobre un `Unknown custom element`, suponie
> **Hace** que Vue ignore...

Por mantener la coherencia con el resto.

2016-12-20 14:42 UTC, llops commented on src/v2/api/index.md
> +  Haz que Vue ignore elementos personalizados definidos fuera de Vue (e.g., utilizando los APIs de Web Components). De lo contrario, lanzará una advertencia sobre un `Unknown custom element`, suponie
En España API es femenino (la API, las APIs) ya que viene de "**La** interfaz de programación de aplicaciones".
Más info: http://www.fundeu.es/consulta/la-api-o-el-api-26405/

No sé si en los países de Sudamérica esto cambia...

2016-12-20 14:42 UTC, llops commented on src/v2/api/index.md
> +  Haz que Vue ignore elementos personalizados definidos fuera de Vue (e.g., utilizando los APIs de Web Components). De lo contrario, lanzará una advertencia sobre un `Unknown custom element`, suponie
e.g. sería **p. ej.**
Más info: http://www.fundeu.es/consulta/por-ejemplo-1687/

2016-12-20 14:42 UTC, llops commented on src/v2/api/index.md
> +  Haz que Vue ignore elementos personalizados definidos fuera de Vue (e.g., utilizando los APIs de Web Components). De lo contrario, lanzará una advertencia sobre un `Unknown custom element`, suponie
Reformulo la frase, sólo para hacer notar que a veces quitando alguna palabra literal o cambiando el tiempo verbal queda la oración más "ligera" (creo :) )

> De lo contrario, lanzará una advertencia sobre un `Unknown custom element`, suponiendo se haya olvidado registrar un componente global o haya escrito mal un nombre de componente.

De lo contrario, lanzará una advertencia _Unknown custom element_ asumiendo que ha olvidado registrar un componente global o que ha escrito mal el nombre.

2016-12-20 14:58 UTC, llops commented on src/v2/api/index.md
> +- **Por defecto:** Lanza un error en vez
Releyendo veo que lo de "en tiempo de compilación" no tiene nada que ver jajaja
En fin, si veis bien "en el lugar" pues adelante.

2016-12-20 14:59 UTC, llops commented
¡Ahí van mis sugerencias!

Y de manera general:
Verbos:  emplear la 3ª persona del presente subjuntivo (Inicie por inicia, etc.)
Sustituir el tuteo por el tratamiento de usted.

Buen trabajo Zahir :)

2016-12-21 02:55 UTC, miljan-aleksic commented on src/v2/api/index.md
> +- **Por defecto:** Lanza un error en vez
>Genera un error al instante

2016-12-21 03:01 UTC, miljan-aleksic commented on src/v2/api/index.md
> +`Vue.config` es un objeto que contiene las configuraciones globales de Vue. Puedes modificar sus propiedades enumeradas a continuación antes de iniciar tu aplicación:
Voto por la segunda opción 👍

2016-12-21 08:35 UTC, llops commented on src/v2/api/index.md
> +- **Por defecto:** Lanza un error en vez
De todo lo propuesto "al instante" creo que es lo que más me gusta también 👍

2016-12-21 13:14 UTC, zgudino commented on src/v2/api/index.md
> +  La estrategia de combinación recibe el valor de esa opción definida en las instancias padre e hijo como primer y segundo argumentos, respectivamente. La instancia Vue de contexto se pasa como terce
Corregido y agregado al siguiente push.

2016-12-21 13:15 UTC, zgudino commented on src/v2/api/index.md
> +  // asegurate de configurarlo de forma sincronizada inmediatamente después de cargar Vue
Corregido y agregado al siguiente push.

2016-12-21 13:15 UTC, zgudino commented on src/v2/api/index.md
> +  Configura si deseas permitir inspección [vue-devtools](https://github.com/vuejs/vue-devtools). El valor por defecto de esta opcion es `true` en compilaciones de desarrollo y `false` en compilacione
Corregido y agregado al siguiente push.

2016-12-21 13:17 UTC, zgudino commented on src/v2/api/index.md
> +- **Por defecto:** Lanza un error en vez
"al instante" encaja perfectamente sin embargo, IMO prefiero __lanza un error al instante__.
Lo podemos dejar a voto mayoritario?

2016-12-21 13:33 UTC, llops commented on src/v2/api/index.md
> +- **Por defecto:** Lanza un error en vez
Pues deja _lanza_ si te gusta más, ningún problema ;)

2016-12-21 13:40 UTC, zgudino commented on src/v2/api/index.md
> +  Asigna un manejador para errores no detectados durante render y watchers del componente. El manejador es llamado con el error y la instancia Vue.
Buenas anotaciones ambos. Yo prefiero:
>...durante render (renderizado) y watchers (observaciones) del componente.

Es muy cierto que ambos términos cuentan con traducción en Español, opino que primero se menciono en Ingles y, en paréntesis, traducción en Español.

2016-12-21 13:42 UTC, zgudino commented on src/v2/api/index.md
> +  La estrategia de combinación recibe el valor de esa opción definida en las instancias padre e hijo como primer y segundo argumentos, respectivamente. La instancia Vue de contexto se pasa como terce
Con pruebas no me puedo oponer 😝. Gracias @llops !

2016-12-21 13:52 UTC, zgudino commented on src/v2/api/index.md
> +  Haz que Vue ignore elementos personalizados definidos fuera de Vue (e.g., utilizando los APIs de Web Components). De lo contrario, lanzará una advertencia sobre un `Unknown custom element`, suponie
Corregido. Adicional, agrego traducción del mensaje de advertencia:
>...advertencia sobre un _`Unknown custom element`_ (_Elemento personalizado desconocido_),

2016-12-21 13:54 UTC, zgudino commented on src/v2/api/index.md
> +`Vue.config` es un objeto que contiene las configuraciones globales de Vue. Puedes modificar sus propiedades enumeradas a continuación antes de iniciar tu aplicación:
Corregido y agregado al siguiente push.

2016-12-21 13:59 UTC, zgudino commented on src/v2/api/index.md
> +  La estrategia de combinación recibe el valor de esa opción definida en las instancias padre e hijo como primer y segundo argumentos, respectivamente. La instancia Vue de contexto se pasa como terce
Corregido y agregado al siguiente push.

2016-12-21 14:19 UTC, zgudino commented on src/v2/api/index.md
> +  Haz que Vue ignore elementos personalizados definidos fuera de Vue (e.g., utilizando los APIs de Web Components). De lo contrario, lanzará una advertencia sobre un `Unknown custom element`, suponie
@llops 
>En España API es femenino (la API, las APIs) ya que viene de "La interfaz de programación de aplicaciones".
Más info: http://www.fundeu.es/consulta/la-api-o-el-api-26405/
>
> No sé si en los países de Sudamérica esto cambia...

En Panama es mas común "el API, los APIs". Sin embargo, me parece mejor tu propuesta 👍 

Corregido y agregado al siguiente push.

2016-12-21 15:17 UTC, zgudino commented on src/v2/api/index.md
> +  Haz que Vue ignore elementos personalizados definidos fuera de Vue (e.g., utilizando los APIs de Web Components). De lo contrario, lanzará una advertencia sobre un `Unknown custom element`, suponie
Corregido y agregado al siguiente push.

2016-12-21 22:28 UTC, llops requested changes
Hay pequeñas confusiones con los tiempos verbales. Cuando hablamos de la configuración, usamos el Presente de Indicativo, ya que es LA OPCIÓN quien "define estrategias", "suprime advertencias", etc. No se debe utilizar el Imperativo, ya que sino sería el usuario: "configure (usted) el permiso", "asigne (usted) un manejador", etc.

2016-12-21 22:28 UTC, llops commented on src/v2/api/index.md
> +  Configure el permiso de inspección de [vue-devtools](https://github.com/vuejs/vue-devtools). El valor por defecto de esta opcion es `true` en compilaciones de desarrollo y `false` en compilaciones
1) Configur**a** 
2) ... para habilitar **la** inspección en ...

2016-12-21 22:28 UTC, llops commented on src/v2/api/index.md
> +    // maneje error
manejar error

2016-12-21 22:28 UTC, llops commented on src/v2/api/index.md
> +  Asigne un manejador para errores no detectados durante renderizado y watchers del componente. El manejador es llamado con el error y la instancia Vue.
Asign**a**

2016-12-21 22:28 UTC, llops commented on src/v2/api/index.md
> +  Asigne un manejador para errores no detectados durante renderizado y watchers del componente. El manejador es llamado con el error y la instancia Vue.
Siento ser pesado, pero _...durante renderizado y watchers del componente._ no tiene mucho sentido.

Estamos hablando del **proceso** de renderizado y del **proceso** de observación. Un _watcher_ sí que es un término en sí, y me parecerá bien no traducirlo en páginas como el ciclo de vida de una instancia Vue, donde se hace referencia a él y en el código del componentes aparece como tal, etc; pero creo que esto es un caso distinto. Aquí lo que queremos comunicar es que se asigna un manejador para los errores mientras se observa el componente.

Vuelvo a proponer esto, y ya ni siquiera el término en inglés entre paréntesis :)
> ... durante **el** renderizado y **la** observación del componente.

2016-12-21 23:18 UTC, miljan-aleksic commented on src/v2/api/index.md
> +  Asigne un manejador para errores no detectados durante renderizado y watchers del componente. El manejador es llamado con el error y la instancia Vue.
Estoy de acuerdo con llops, por eso propuse *...durante renderizado y la ejecución de los watchers (observadores) del componente*. La propuesta de llops también me parece correcta.

2016-12-22 02:22 UTC, miljan-aleksic commented on src/v2/api/index.md
> +  Configura el permiso de inspección de [vue-devtools](https://github.com/vuejs/vue-devtools). El valor por defecto de esta opcion es `true` en compilaciones de desarrollo y `false` en compilaciones
Opción lleva acento

2016-12-22 02:30 UTC, miljan-aleksic commented on src/v2/api/index.md
> +  Hace que Vue ignore elementos personalizados definidos fuera de Vue (p. ej., utilizando las APIs de Web Components). De lo contrario, lanzará una advertencia sobre un _`Unknown custom element`_ (_E
>De lo contrario, lanzará una advertencia _`Unknown custom element`_ (_Elemento personalizado desconocido_)...

Me parece mejor así.

2016-12-22 02:56 UTC, zgudino commented on src/v2/api/index.md
> +  Configura el permiso de inspección de [vue-devtools](https://github.com/vuejs/vue-devtools). El valor por defecto de esta opcion es `true` en compilaciones de desarrollo y `false` en compilaciones
Corregido.

2016-12-22 02:56 UTC, zgudino commented on src/v2/api/index.md
> +  Hace que Vue ignore elementos personalizados definidos fuera de Vue (p. ej., utilizando las APIs de Web Components). De lo contrario, lanzará una advertencia sobre un _`Unknown custom element`_ (_E
Corregido.

2016-12-22 03:04 UTC, miljan-aleksic approved these changes

2016-12-22 19:21 UTC, llops reviewed
Último feedback. ¡Lo juro! :)

2016-12-22 19:21 UTC, llops commented on src/v2/api/index.md
> +  Asigna un manejador para errores no detectados durante el renderizado y la observación del componente. El manejador es llamado con el error y la instancia Vue.
Se me pasó esta frase, pero releyendo veo que es una traducción demasiado literal. Propongo:

> **Se llama** al manejador con el error y la instancia Vue.

Al contrario que en inglés, en español es poco natural utilizar la forma pasiva. No es incorrecta, pero como norma general mejor evitarla. ¿Os parece bien?

2016-12-22 19:21 UTC, llops commented on src/v2/api/index.md
> +  // asegúrese de configurarlo de forma sincronizada inmediatamente después de cargar Vue
De forma sincronizada no suena mal, pero se suele utilizar **síncrona**.
Creo que se ve más claro si la opción fuera **asíncrona**, que no diríamos **de forma asincronizada"

2016-12-22 19:21 UTC, llops commented on src/v2/api/index.md
> +  > [Sentry](https://sentry.io), un servicio de seguimiento de errores, proporciona [integración oficial](https://sentry.io/for/vue/) utilizando esta opción.
Otra traducción demasiado literal, creo. Propuesta:

> Esta opción utiliza [Sentry](https://sentry.io), un servicio de seguimiento de errores que cuenta con [integración oficial](https://sentry.io/for/vue/).

2016-12-22 19:21 UTC, llops commented on src/v2/api/index.md
> +  Hace que Vue ignore elementos personalizados definidos fuera de Vue (p. ej., utilizando las APIs de Web Components). De lo contrario, lanzará una advertencia _`Unknown custom element`_ (_Elemento p
Una frase un tanto redundante (también la versión inglesa) + "falso gerundio" (using). Propuesta:

> Ignora elementos personalizados definidos fuera de Vue (p. ej., si usa las APIs de Web Components).

2016-12-22 19:34 UTC, zgudino commented on src/v2/api/index.md
> +  // asegúrese de configurarlo de forma sincronizada inmediatamente después de cargar Vue
`//asegúrese de configurarlo de forma síncrona inmediatamente después de cargar Vue` asi?

2016-12-22 19:38 UTC, zgudino commented on src/v2/api/index.md
> +  Asigna un manejador para errores no detectados durante el renderizado y la observación del componente. El manejador es llamado con el error y la instancia Vue.
A mi, cualquier que decidan.

2016-12-22 19:41 UTC, zgudino commented on src/v2/api/index.md
> +  > [Sentry](https://sentry.io), un servicio de seguimiento de errores, proporciona [integración oficial](https://sentry.io/for/vue/) utilizando esta opción.
Corregido.

2016-12-22 19:48 UTC, zgudino commented on src/v2/api/index.md
> +  Hace que Vue ignore elementos personalizados definidos fuera de Vue (p. ej., utilizando las APIs de Web Components). De lo contrario, lanzará una advertencia _`Unknown custom element`_ (_Elemento p
Agrego esta propuesta.

2017-02-05 07:32 UTC, miljan-aleksic commented
@zgudino, dime si hay algo por nuestras parte pendiente en este PR.

2017-02-06 22:36 UTC, zgudino commented
@miljan-aleksic acabo de ver una anotación de @llops, [96](https://github.com/vuejs-es/vuejs.org/pull/6#discussion_r93681457), que no había prestado atención.

Permite corregirla mas tarde que llegue a casa.
Gracias ambos!

2017-08-30 03:43 UTC, merged