[API Translate] Special Attributes
vuejs-es/vuejs.org pull request #63
Opened 2018-09-19 09:53 UTC by UchihaCFC

He agregado la traducción de la sección Special Atributtes de la api, con ésta ya sólo nos quedaría uan sección más para terminar de traducir toda esta sección de la API.

2018-09-19 11:36 UTC, miljan-aleksic requested changes
Muchas gracias! Te dejo mis comentarios.

2018-09-19 11:36 UTC, miljan-aleksic commented on src/v2/api/index.md
> +  Cuando se usa en un elemento normal, solo escucha **eventos DOM nativos**. Cuando se utiliza en un componente de elemento personalizado, también escucha **eventos personalizados** emitidos en ese c
`componente secundario` podria confundir. Recomiendo usar traduccion literal `component hijo` o simplemente `componente`.

2018-09-19 11:36 UTC, miljan-aleksic commented on src/v2/api/index.md
> +  Escuchar eventos personalizados en un componente secundario (se llama al controlador cuando se emite "my-event" en el hijo):
Mismo caso aqui con lo del componente secundario.

2018-09-19 11:36 UTC, miljan-aleksic commented on src/v2/api/index.md
> +  Cuando se utiliza para enlazar el atributo `class` o` style`, admite tipos de valores adicionales como Array u Objetos. Consulte la sección de la guía vinculada a continuación para obtener más deta
Pequeña falta ortografica en `class` o` style`, deberia ser `class` o `style`.

2018-09-19 11:36 UTC, miljan-aleksic commented on src/v2/api/index.md
> +  <!--Vincular un atributo del DOM con un modificador prop -->
falta un espacio despues de `<!--`

2018-09-19 11:36 UTC, miljan-aleksic commented on src/v2/api/index.md
> +  El modificador `.camel` permite 'camelizar' un nombre de atributo` v-bind` cuando se usan plantillas in-DOM, p. el atributo SVG `viewBox`:
La abreviatura `por ejemplo` parece incompleta, deberia ser `p.e` o dejarlo sin abreviar.

2018-09-19 11:36 UTC, miljan-aleksic commented on src/v2/api/index.md
> +  - [`.lazy`](../guide/forms.html#lazy) - escucha los eventos `change` en lugar de` input`
falta ortografica, en lugar de`

2018-09-19 11:36 UTC, miljan-aleksic commented on src/v2/api/index.md
> +  - [Componentes: componentes de entrada de formularios con eventos personalizados](../guide/components.html#Form-Input-Components-using-Custom-Events)
no hay dos puntos en el texto original.

2018-09-19 11:36 UTC, miljan-aleksic commented on src/v2/api/index.md
> +  El `<div>` no estará visible hasta que la compilación haya finalizado.
Creo que el verbo correcto es ser, no estar. `...no será visible...`

2018-09-19 11:36 UTC, miljan-aleksic commented on src/v2/api/index.md
> +    <h1>Comentario</h1>
comentario en minuscula

2018-09-19 11:36 UTC, miljan-aleksic commented on src/v2/api/index.md
> +  <my-componente v-once :comment="msg"></my-component>
El codigo no se traduce, solo los comentarios

2018-09-19 11:36 UTC, miljan-aleksic commented on src/v2/api/index.md
> +  - [Sintaxis de enlace de datos: interpolaciones](../guide/syntax.html#Text)
el texto original no tiene dos puntos

2018-09-19 11:36 UTC, miljan-aleksic commented on src/v2/api/index.md
> +  Los hijos del mismo padre común deben tener **keys únicas**. Las `key` duplicadas causarán errores de representación.
`keys`

2018-09-19 11:36 UTC, miljan-aleksic commented on src/v2/api/index.md
> +  `ref` se usa para registrar un referencia a un elemento o un componente secundario. La referencia se registrará en el objeto `$refs` del componente principal. Si se usa en un elemento DOM simple, l
component hijo, no secundario. Componenete padre, no principal.

2018-09-19 11:36 UTC, miljan-aleksic commented on src/v2/api/index.md
> +  Se usa en contenido insertado en componentes secundarios para indicar a qué `slot` nombrado pertenece el contenido.
componentes hijos

2018-09-19 11:36 UTC, miljan-aleksic commented on src/v2/guide/migration.md
> +> Woah - ¡esta página es súper larga! ¿Eso significa que la versión 2.0 es completamente diferente y tendrá que aprender los conceptos básicos una y otra vez? ¿la migración será prácticamente imposib
En este caso la pregunta la hace el lector, por lo que debe usarse la primera persona del singular.

Juntar las dos preguntas `... una y otra vez y la migración...`

2018-09-19 11:36 UTC, miljan-aleksic commented on src/v2/guide/migration.md
> +> ¿Cuánto tiempo le llevará migrar una aplicación de Vue 1.x a 2.0?
Cambiar a Primera persona o hacerlo neutral `¿Cuánto tiempo llevará...`

2018-09-19 11:36 UTC, miljan-aleksic commented on src/v2/guide/migration.md
> +> Si actualiza a Vue 2, ¿también tendrá que actualizar Vuex y Vue Router?
Cambiar a primera persona.

2018-09-19 15:50 UTC, UchihaCFC commented
He subido dos push mas con los cambios

2018-09-19 20:01 UTC, miljan-aleksic approved these changes

2018-09-19 20:12 UTC, merged

2018-09-19 20:13 UTC, miljan-aleksic commented
Muchas gracias! Vamos a por la ultima? :)

2018-09-20 11:53 UTC, UchihaCFC commented
Claro! la subo en breve y te aviso