Traducción de components, computed, conditional & custom-directive
vuejs-es/vuejs.org pull request #74
Opened 2019-01-25 01:13 UTC by siddharta1337

- src/v2/guide/components.md  
- src/v2/guide/computed.md
- src/v2/guide/conditional.md
- src/v2/guide/custom-directive.md

2019-01-25 11:23 UTC, miljan-aleksic requested changes
Excelente trabajo Carlos! Tan solo en algunos parafos la traduccion se revirtió, los he marcado en el review pero pueden haber mas.

2019-01-25 11:23 UTC, miljan-aleksic commented on src/v2/guide/components.md
> -  <h1 slot="header">Aquí puede haber un título</h1>
Se revertió la traducción.

2019-01-25 11:23 UTC, miljan-aleksic commented on src/v2/guide/components.md
> -  <p>Un párrafo para el contenido principal.</p>
Se revertió la traducción.

2019-01-25 11:23 UTC, miljan-aleksic commented on src/v2/guide/components.md
> +  <p slot="footer">Here's some contact info</p>
Se revertió la traducción.

2019-01-25 11:23 UTC, miljan-aleksic commented on src/v2/guide/components.md
> +    <h1>Here might be a page title</h1>
Se revertió la traducción.

2019-01-25 11:23 UTC, miljan-aleksic commented on src/v2/guide/components.md
> +    <p>Here's some contact info</p>
Se revertió la traducción. Revisa los paragrafos anteriores tambien.

2019-01-25 11:23 UTC, miljan-aleksic commented on src/v2/guide/components.md
> +A pesar de la existencia de props y eventos, sometimes you might still need to directly access a child component in JavaScript. To achieve this you have to assign a reference ID to the child componen
Se revertió la traducción.

2019-01-25 11:23 UTC, miljan-aleksic commented on src/v2/guide/components.md
> +Failed to mount component: template or render function not defined.
Se revertió la traducción.

2019-01-25 11:23 UTC, miljan-aleksic commented on src/v2/guide/components.md
> +Problema resuelto!
En Español, al menos en España, los signos de puntuacion se ponen en los dos lados.

2019-01-25 11:23 UTC, miljan-aleksic commented on src/v2/guide/components.md
> +    This will only be displayed if there is no content
Se revertió la traducción.

2019-01-25 11:23 UTC, miljan-aleksic commented on src/v2/guide/components.md
> +  <h2>I'm the child title</h2>
Se revertió la traducción.

2019-01-25 11:23 UTC, miljan-aleksic commented on src/v2/guide/components.md
> +  <h1>I'm the parent title</h1>
Se revertió la traducción.

2019-01-25 11:23 UTC, miljan-aleksic commented on src/v2/guide/components.md
> +    <p>This is some more original content</p>
Se revertió la traducción.

2019-01-25 11:23 UTC, miljan-aleksic commented on src/v2/guide/components.md
> +    <p>This is some more original content</p>
Se revertió la traducción. Revisa los parafos anteriores.

2019-01-25 15:55 UTC, siddharta1337 commented
@miljan-aleksic ¡ gracias por la revisión! listos los cambios.

2019-01-25 23:21 UTC, miljan-aleksic requested changes

2019-01-25 23:21 UTC, miljan-aleksic commented on src/v2/guide/components.md
> +The rendered result will be:
Otro mas :)

2019-01-26 05:42 UTC, siddharta1337 commented
@miljan-aleksic  excelente ojo para atrapar errores!! esa se me escapó del todo!
 
Le di una revisión extra al doc, parece que esta vez si está listo :D

2019-01-26 19:32 UTC, merged

2019-01-26 19:33 UTC, miljan-aleksic commented
Gracias @siddharta1337, si te animas a por mas tan solo dimelo :)